### ISSUE TITLE
What is best practice for large amounts of Unit Tests?

### ISSUE THREAD

**Issue by DamienDennehy** [martincostello/sqllocaldb#291]
We have a solution with 2000 Unit Tests, across multiple projects/assemblies using xUnit.
We currently run the tests against an instance of SQL Server and the tests take roughly 10-20 minutes to run.
We want to make this more self contained and use sqllocaldb and each test would have its own database.

I've been using it and it works very well but do you have any recommendations as to how to apply it to this scale?
Some questions...

We have about 400 collections of tests with about 50 tests each.

**Number of instances**
- Should we have an instance of LocalDB for each test? So over the lifetime of the test run 2000 instances and 2000 databases would be created?
- Or one instance per collection, with each test creating its own DB? 400 instances would be created here, 2000 databases.
- Should we simply create one instance per test run? So 1 instance total, 2000 databases.

**Performance/running tests in parallel?** 

When we switched over to fully using sqllocaldb our tests times went from a max of 20 minutes to 70 minutes.
It looks like for us at least when more than 4 instances are running in parallel strange things can occur.
Should we run just one instance at any one time?

EDIT: The bug label can be removed from this, it's just a query.

**Comment by martincostello** [comment]
Hi Damien - thanks for your question (and the ☕)!

From experience, we've done something similar to the below for using SQL LocalDB for tests. I've used **bold** and _italics_ to try and call out the nuances as well as xunit-ish terminology:
  1. Create a single LocalDB **instance** for the test _run/assembly_ (for example keeping it in a shared _collection fixture_)
  1. Create a single SQL **database** in that shared **instance** per test _class/fixture_
  1. Clear/reseed the **database** in each test _class_ per _fact/theory+row_

The idea here is to try and minimise the setup and tear-down overhead whilst balancing keeping the context of tests' pre and post conditions from interfering with other test(s) due to shared state.

By far the most expensive operation is creating an instance (the order of 1-2 seconds if I remember correctly), followed by the smaller overhead of create a database with the relevant schema and/or data for your System-Under-Test.

When we first started using this approach, we found it got slower and slower as the number of tests went up, and the primary source of that overhead was creating, starting and stopping LocalDB instances.

It's your call based on the context of your particular setup as to how much _database_ setup code can be shared, for example whether you can create one database and share it, or need to create a different database for each test or test class, whether you can share the database but need to empty the tables between tests etc.

To give you a flavour of this sort of thing, below are a couple of classes I've edited from one of the integration test suites for an application I help maintain that shows the reuse principal via fixtures. In this case, the tests only do inserts, so we just share one database for all the tests and just let the rows accumulate without any tidy up, other than deleting the SQL LocalDB instance at the end of the test run.

I hope this helps - let me know if you need any further clarity.

```csharp
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using MartinCostello.Logging.XUnit;
using MartinCostello.SqlLocalDb;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.Data.SqlClient;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Xunit;
using Xunit.Abstractions;

namespace MyApplication.IntegrationTests
{
    [CollectionDefinition(Name)]
    public class HttpServerCollection : ICollectionFixture<HttpServerFixture>
    {
        public const string Name = "HTTP Server";
    }

    public sealed class HttpServerFixture : WebApplicationFactory<Startup>, ITestOutputHelperAccessor
    {
        public HttpServerFixture()
        {
            Database = new DatabaseFixture(this);
        }

        public ITestOutputHelper OutputHelper { get; set; }

        public DatabaseFixture Database { get; }

        public void ClearOutputHelper()
        {
            OutputHelper = null;
        }

        public void SetOutputHelper(ITestOutputHelper value)
        {
            OutputHelper = value;
        }

        protected override void ConfigureWebHost(IWebHostBuilder builder)
        {
            base.ConfigureWebHost(builder);

            builder
                .ConfigureLogging((p) => p.ClearProviders().AddXUnit(this))
                .ConfigureAppConfiguration(
                    (_, config) =>
                    {
                        if (Database.IsLocalDBInstalled)
                        {
                            var initialData = new Dictionary<string, string>()
                            {
                                // Configure the connection string for your application as appropriate
                                ["MyDatabaseConnectionString"] = Database.ConnectionString,
                            };

                            config.AddInMemoryCollection(initialData);
                        }
                    });
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            Database?.Dispose();
        }
    }

    public sealed class DatabaseFixture : IDisposable
    {
        private bool _disposed;

        public DatabaseFixture(ITestOutputHelperAccessor accessor)
        {
            Accessor = accessor;
        }

        ~DatabaseFixture()
        {
            DisposeInternal();
        }

        public bool IsLocalDBInstalled
        {
            get
            {
                EnsureInitialized();
                return LocalDB.IsLocalDBInstalled();
            }
        }

        public string ConnectionString
        {
            get
            {
                if (!IsLocalDBInstalled)
                {
                    throw new NotSupportedException("Microsoft SQL LocalDB is not installed.");
                }

                return Database.ConnectionString;
            }
        }

        private ITestOutputHelperAccessor Accessor { get; }

        private SqlLocalDbApi LocalDB { get; set; }

        private TemporarySqlLocalDbInstance Database { get; set; }

        public void Dispose()
        {
            DisposeInternal();
            GC.SuppressFinalize(this);
        }

        private void DisposeInternal()
        {
            if (!_disposed)
            {
                Database?.Dispose();
                LocalDB?.Dispose();

                _disposed = true;
            }
        }

        private void EnsureInitialized()
        {
            if (LocalDB != null)
            {
                return;
            }

            LocalDB = new SqlLocalDbApi(Accessor.OutputHelper.ToLoggerFactory());

            if (LocalDB.IsLocalDBInstalled())
            {
                Database = LocalDB.CreateTemporaryInstance();

                using var connection = new SqlConnection(Database.ConnectionString);
                connection.Open();

                // TODO Put your common database initialization code here (e.g. creating tables and seeding data)
            }
        }
    }

    [Trait("Category", "SQL")]
    [Collection(HttpServerCollection.Name)]
    public sealed class MyDatabaseTests
    {
        public MyDatabaseTests(HttpServerFixture fixture, ITestOutputHelper outputHelper)
        {
            Fixture = fixture;
            Fixture.SetOutputHelper(outputHelper);
        }

        private HttpServerFixture Fixture { get; }

        [SkippableFact]
        public async Task My_Application_Does_Things_That_Rely_On_My_Database_Correctly()
        {
            // Make sure SQL LocalDB is installed
            Skip.IfNot(Fixture.Database.IsLocalDBInstalled, "Microsoft SQL LocalDB is not installed.");

            // Seed your database with any data you need
            using var connection = new SqlConnection(Fixture.Database.ConnectionString);
            using var command = new SqlCommand("INSERT INTO [Foo] ([Bar]) VALUES (N'Baz')", connection);
            await command.ExecuteNonQueryAsync();

            // Start the application under test
            await EnsureServiceRunningAsync();

            // TODO Your test code
        }

        private async Task EnsureServiceRunningAsync()
        {
            using var client = Fixture.CreateClient();
            using var response = await client.GetAsync(string.Empty);
        }
    }
}
```

**Comment by DamienDennehy** [comment]
This is very very helpful!
I implemented it this morning and we found a dramatic difference in running the tests, most notably on smaller VMs.
