### ISSUE TITLE
Delete instance files in %USERPROFILE%

### ISSUE THREAD

**Issue by mu88** [martincostello/sqllocaldb#449]
## Describe the bug
When running the following snippet, not all instance files are deleted. Within the `%USERPROFILE%`, the following two files are still there:
- `<<MyDatabase>>.mdf`
- `<<MyDatabase>>_log.ldf`

This leads to further errors when trying to recreate the database.

## Steps To reproduce
```cs
using var localDb = new SqlLocalDbApi();
localDb.DeleteInstance("MyInstance", true);
```

## Expected behaviour
There should be no more files belonging to the instance `MyInstance` under `%USERPROFILE%`.

## Actual behaviour
There are still two files belonging to the instance `MyInstance` under `%USERPROFILE%`:
- `<<MyDatabase>>.mdf`
- `<<MyDatabase>>_log.ldf`

## System information
- OS: Windows 10, Version 20H2
- Library Version: `3.0.1`
- SQL LocalDB version: `13.0`
- .NET version:  
```
.NET SDK (reflecting any global.json):
 Version:   6.0.100-rc.1.21463.6
 Commit:    e627d556a1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-rc.1.21463.6\

Host (useful for support):
  Version: 6.0.0-rc.1.21451.13
  Commit:  d7619cd4b1

.NET SDKs installed:
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.2.300 [C:\Program Files\dotnet\sdk]
  3.1.412 [C:\Program Files\dotnet\sdk]
  5.0.206 [C:\Program Files\dotnet\sdk]
  5.0.303 [C:\Program Files\dotnet\sdk]
  5.0.401 [C:\Program Files\dotnet\sdk]
  6.0.100-rc.1.21463.6 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.1.21452.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.1.21451.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-rc.1.21451.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

## Additional context
I think all existing databases within the instance should be deleted [here](https://github.com/martincostello/sqllocaldb/blob/fd6c2262ec4f75a0564c1558d6f6c30534e6f2db/src/SqlLocalDb/SqlLocalDbApi.cs#L1187).

**Comment by martincostello** [comment]
Is the instance still running somewhere else? The library makes a best attempt to delete the directory containing the instance files, but if they are still in use by another (or the same) process it will fail, which is then just handled and logged:

https://github.com/martincostello/sqllocaldb/blob/fd6c2262ec4f75a0564c1558d6f6c30534e6f2db/src/SqlLocalDb/SqlLocalDbApi.cs#L1191-L1194

The library can't guarantee nothing else on the machine is using the files, and can't force them to be deleted if they are.

**Comment by martincostello** [comment]
Ah, sorry, I missed that in the description. I also assumed it was where it was looking, because I haven't had the change the implementation for quite some time so it's not all fresh in my head anymore.

If you can show some screenshots/examples/full paths of the "missing" deleted files, then I can look into being able to have it attempt some further additional tidying up of files.

It's also _possible_ that where the files are located has changed over time since it was originally implemented back in ~2014 and some of the files have migrated to being split with an additional location. If not, then this is a 7 year old bug and you're the first to notice 😄

**Comment by martincostello** [comment]
Right, having looked into this, this isn't a bug.

The databases created by SQL LocalDB are created at a location controlled by SQL Server itself, and as specified by its defaults and the connection string the user provides. They are not files intrinsically associated with the _instance_, because they are portable and can be attached to any other instance at any time.

There is no way for the library to know _what_ you choose to do with the instance once you create it, and there is no way for it to know what the name of any database files you chose to create with it to delete would be. Guessing at names would be dangerous as it could lead to data loss if the guess was wrong. It is also not possible for it to determine what directory the database is in. `%USERPROFILE%` is just the SQL Server LocalDB default, it could be placed somewhere else.

The onus is on you as the creator of the database(s) to keep track of them and tidy them up as your requirements may dictate.

For example, there is this code in the test console app:

https://github.com/martincostello/sqllocaldb/blob/fd6c2262ec4f75a0564c1558d6f6c30534e6f2db/src/TestApp/Program.cs#L101-L102

After the first line is executed, `%USERPROFILE%\MyDatabase.mdf` and `%USERPROFILE%\MyDatabase_log.ldf` will both exist. After the second line is executed, both files will be deleted by the SQL Server instance.

**Comment by martincostello** [comment]
No problem - thanks for raising it anyway!
